USE [master]
GO

/****** Object:  Audit [AUDIT_OBJECT_DEV]    Script Date: 01/09/2022 18:17:36 ******/
CREATE SERVER AUDIT [AUDIT_OBJECT_DEV]
TO FILE 
(	FILEPATH = N'F:\AUDIT_SQL\' -- DEFININDO ONDE SERÁ GRAVADO O ARQUIVO
	,MAXSIZE = 51200 MB --TAMANHO MAXIMO DE CRESCIMENTO **QUANDO ATINGIR O TAMANHO, O SQL CRIA MAIS UM ARQUIVO**
	,MAX_ROLLOVER_FILES = 2147483647
	,RESERVE_DISK_SPACE = OFF -- SUGIRO DEIXAR OFF PARA IR RESERVANDO CONFORME UTILIZAÇÃO, CASO CONTRARIO ELE RESERVARÁ O TAMANHHO DEFINIDO NO MAXSIZE
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)--, AUDIT_GUID = 'c3b993ff-ac7c-443f-b0ab-cf9582893a57')
WHERE (NOT [statement] like '%UPDATE STATISTICS%') --FILTRO
ALTER SERVER AUDIT [AUDIT_OBJECT_DEV] WITH (STATE = ON)
GO


