USE [master]
GO

CREATE SERVER AUDIT SPECIFICATION [AUDIT_DEV_DDL]
FOR SERVER AUDIT [AUDIT_OBJECT_DEV]
ADD (SCHEMA_OBJECT_CHANGE_GROUP), --AUDIT TYPE 1
ADD (SERVER_OBJECT_CHANGE_GROUP) -- AUDIT TYPE 2
WITH (STATE = ON)
GO


